### ISSUE TITLE
Playlists

### ISSUE THREAD

**Issue by sakofchit** [iberatkaya/playify#1]
Hey!

Fantastic plugin :). Works pretty well overall

Do you have any plans of implementing support for playlists?

**Comment by iberatkaya** [comment]
Hello! :D

I’m glad you liked the plugin. I am not sure if I will add native playlists for the plugin in the near future, but you can implement your own playlists. A playlist is basically a queue of songs. You can store the unique id’s of each song in a local storage, and play music from that list of id’s in your own app by setting a queue. Please let me know if you think this is not a good approach. Then I may look more into adding playlists.

**Comment by sakofchit** [comment]
Ah gotcha, I saw this https://developer.apple.com/documentation/mediaplayer/mpmediaplaylist and assumed it'd be trivial to add support for it too. Might submit a PR if I can do it

Cause in my app I was using this plugin to only fetch & control songs from the Apple Music app, so I figured it'd be nice to be able to fetch/display playlists from the Apple Music app if possible

Great work so far though! It took me like 2 months to find a flutter plugin that worked with Apple Music––you should definitely share it in https://www.reddit.com/r/flutterdev :)

**Comment by iberatkaya** [comment]
I guess it is important to also view and create playlists from Apple Music. I will look more into it. A PR is always welcomed too. 

Thanks again for the kind words. Feel free to add more suggestions since this is a fairly new plugin! I will share it as soon as I can :D
