### ISSUE TITLE
Can we play full duration song ?

### ISSUE THREAD

**Issue by kalismeras61** [iberatkaya/playify#7]

**Comment by iberatkaya** [comment]
Yes, you can play any song in the Music Library with its full duration.

**Comment by kalismeras61** [comment]
Thanks. I didn't notice the maintainers is from Turkey :)) . One more thing how is the player behavior ? Can we control music over the notification center ?

**Comment by iberatkaya** [comment]
Nice to see another Flutter Developer from Turkey :D. Yes, Playify uses `MPMusicPlayerController.systemMusicPlayer` from the MediaPlayer Library to control the Music Player. 

> The system music player employs the built-in Music app on your behalf. On instantiation, it takes on the current Music app state, such as the identification of the now-playing item. If a user switches away from your app while music is playing, that music continues to play. The Music app then has your music player’s most recently-set repeat mode, shuffle mode, playback state, and now-playing item.

You can read more about this [here](https://developer.apple.com/documentation/mediaplayer/mpmusicplayercontroller).

**Comment by kalismeras61** [comment]
Yeah, i am working with flutter almost 2.5 years :)) Okay, thank for the prompt response. Will try it, thanks.
