### ISSUE TITLE
Type mismatch: inferred type is String? but String was expected

### ISSUE THREAD

**Issue by xxjonesriderxx** [iberatkaya/playify#9]
I got following error on Android so I couldn't build the App: 

> C:\Users\user\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\playify-2.0.0\android\src\main\kotlin\com\kaya\playify\playify\PlayifyPlayer.kt: (76, 34): Type mismatch: inferred type is String? but String was expected

I solved this with commenting line 76 in PlayifyPlayer. The causing line was `Log.d("playify", albumArt)`

**Comment by iberatkaya** [comment]
Hello. Thanks for the catch. I see that you are using this plugin for Android. I am still in the process of adding Android support to Playify. It would be best to wait until Android support is completely added (since it is only partially functional), or feel free to contribute to the package.
